# HTTP Server
[server]
	Address     = ":3100"
	ServerRoot  = "public"
	ServerAgent = "farcai"
	LogPath     = "/tmp/logs/server"

# Logger.
[logger]
    Path        = "/tmp/logs"
    Level       = "all"
    Stdout      = true

[database]
    type = "mysql"
    link = "test:test@tcp(127.0.0.1:3306)/blog_db"

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]
    [viewer.Data]
        Title = "JJXie"
        Description = "JJXie的个人博客"
        Logo = "/resource/images/logo.png"
        Navigation = ["首页","/", "归档","/pigeonhole", "关于","/about"]
        Github = "https://github.com/jianjunx"
        Gitee = "https://gitee.com/JianJunXie"
        Zhihu = "/"
        Weibo = "https://weibo.com/autoshun"
        Avatar = "https://jianjun-1251280787.cos.ap-nanjing.myqcloud.com/assets/avatar_mini.png"
        UserName = "JJ Xie"
        UserDesc = "天上白玉京,十二楼五城 仙人抚我顶,结发受长生"
        CdnURL = "//jianjunxie.gitee.io/es6/md-assets"

# cos
[cos]
    Region = "ap-nanjing"
    Bucket = "jianjun-1251280787"
    Appid = "1251280787"
    Path = "/post"