# HTTP Server
[server]
	Address     = ":3100"
	ServerRoot  = "public"
	ServerAgent = "farcai"
	LogPath     = "/tmp/logs/server"

# Logger.
[logger]
    path        = "/tmp/logs"
    level       = "ERRO"
    stdout      = true
    file        = "{Y-m-d}.log"

[database]
    type = "mysql"
    link = "test:test@tcp(127.0.0.1:3306)/blog_db"
    backup = true # 开启备份
    # 备份目录
    backupPath = "/tmp/logs"
    # 备份到COS
    backupCOS = true
    # 定时任务表达式 每周三 3点执行
    backupCron = "0 3 * * WED"

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]
    [viewer.Data]
        Title = "JJ Xie"
        Description = "JJ Xie 谢建军的个人博客"
        Logo = "/resource/images/logo.png"
        Navigation = ["首页","/", "归档","/pigeonhole", "关于","/about"]
        Github = "https://github.com/jianjunx"
        Gitee = "https://gitee.com/JianJunXie"
        Zhihu = "/"
        Weibo = "https://weibo.com/autoshun"
        Avatar = "https://jianjun-1251280787.cos.ap-nanjing.myqcloud.com/assets/avatar_mini.png"
        UserName = "JJ Xie"
        UserDesc = "一位头发乌黑浓密，不穿格子衫，长得还帅的程序员."
        CdnURL = "//jianjunxie.gitee.io/es6/md-assets"
        Valine = true
        ValineAppid = "UT7JUprfJLmJU9k2fLPDOaqP-MdYXbMMI"
        ValineAppkey = "lD6RiiGKU3H8m57HOFLHwv88"
        ValineServerURL = "//ut7juprf.api.lncldglobal.com"

# cos
[cos]
    Region = "ap-nanjing"
    Bucket = "jianjun-1251280787"
    Appid = "1251280787"
    Path = "/post"
